-- ============================================================================
-- Storage Security: Disable Public INSERT/UPDATE on 'market-assets' Bucket
-- ============================================================================
-- 
-- This migration removes public INSERT and UPDATE permissions on the 
-- 'market-assets' storage bucket, ensuring that only authenticated admins
-- can upload files through the secure server action (getUploadUrl).
--
-- The secure flow:
-- 1. Admin requests upload → Server Action verifies is_admin()
-- 2. Server Action generates signed upload URL with UUID filename
-- 3. Client uploads directly to signed URL (no RLS bypass needed)
-- 4. Public can still READ files (for displaying images on the site)
--
-- Run this migration to secure your storage bucket.
-- ============================================================================

-- First, let's check existing policies on the market-assets bucket
-- (This is informational - you can run this separately to see current state)
-- SELECT * FROM storage.policies WHERE bucket_id = 'market-assets';

-- Drop any existing public INSERT policies on market-assets bucket
-- (Adjust policy names based on your actual policy names)
DROP POLICY IF EXISTS "Public can insert market assets" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can upload market assets" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert" ON storage.objects;

-- Drop any existing public UPDATE policies on market-assets bucket
DROP POLICY IF EXISTS "Public can update market assets" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can update market assets" ON storage.objects;
DROP POLICY IF EXISTS "Public Update" ON storage.objects;

-- Ensure public READ access is still enabled (for displaying images)
-- This policy allows anyone to view/download files from the bucket
DROP POLICY IF EXISTS "Public can read market assets" ON storage.objects;
CREATE POLICY "Public can read market assets"
ON storage.objects FOR SELECT
USING (bucket_id = 'market-assets');

-- Optional: Add a policy for authenticated admins to DELETE files
-- (Only if you want admins to be able to delete files through the UI)
DROP POLICY IF EXISTS "Admins can delete market assets" ON storage.objects;
CREATE POLICY "Admins can delete market assets"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'market-assets' 
    AND auth.uid() IS NOT NULL
    AND is_admin()
);

-- ============================================================================
-- IMPORTANT NOTES:
-- ============================================================================
-- 
-- 1. After running this migration, direct client-side uploads will FAIL
--    (which is exactly what we want for security)
--
-- 2. Only uploads through signed URLs (generated by getUploadUrl server action)
--    will succeed
--
-- 3. The signed URLs are temporary and scoped to a specific file path,
--    preventing unauthorized uploads
--
-- 4. Public READ access remains enabled so images can be displayed on the site
--
-- 5. If you need to manually upload files (e.g., via Supabase Dashboard),
--    you can still do so as an authenticated admin
--
-- ============================================================================
